name: darttutorials
version: 0.0.1
description: practice for dart.
author: Aman Gulati <amangulati075@gmail.com>
homepage: https://github.com/amaan75/Dart_tuts
documentation: https://github.com/amaan75/Dart_tuts#README.md
dependencies:
  image: "^1.1.30"
  http: "^0.11.3+16"
